import type { Metadata } from "next";
import { Roboto } from 'next/font/google'
import "./globals.css";
import Loader from "@/components/loader/loader";

const roboto = Roboto({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Loader />
        {children}
      </body>
    </html>
  );
}
